### ISSUE TITLE
Code coverage: browser tests + upload to coveralls

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/react-fast-compare#11]
- [ ] Hook up coverage in `karma` (see `TODO`s)
- [ ] Join test coverage `lcov` output from both node and karma into a joint upload to coveralls.
- [ ] Re-enable coveralls badge in README.

**Comment by cdierkens** [comment]
@ryan-roemer are we still interested in the ticket or does coveralls provide some advantage over `codecov`?

**Comment by ryan-roemer** [comment]
Nope! Coveralls has been superseded by codecov we’re all good
