### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by jaredpalmer** [FormidableLabs/react-fast-compare#13]
Just shaved 5kb off Formik with this. nbd.

**Comment by chrisbolin** [comment]
@jaredpalmer awesome to hear! what did you replace?

**Comment by jaredpalmer** [comment]
lodash.isequal which i probs should never have been using in the first place.

**Comment by chrisbolin** [comment]
`isEqual` is really convenient and thorough. totally fine to use something like that when you are developing and remove it later for performance/size/features etc.

glad this was helpful!
