### ISSUE TITLE
Circular references, RangeError in prod

### ISSUE THREAD

**Issue by natew** [FormidableLabs/react-fast-compare#30]
*Maintainer's Note: **we need help reproducing this bug in react-fast-compare 2.0.4** (or greater). If you have hit this bug, please help us by submitting a repository or code sandbox that shows the behavior. Note, this library does not support circular objects, only React internal circular objects.* 😃

---

Saw a previous issue, but still getting this in 2.0.1. Here's the output:

![image](https://user-images.githubusercontent.com/12100/42650456-4831f258-85c1-11e8-99c1-95c99626f549.png)

I'm essentially comparing props, nothing too strange. The objects are all non-circular besides the react children. In dev mode it works just fine, in prod (Uglify compressed) it seems to break.

I'm using these opts:

```
new UglifyJsPlugin({
        uglifyOptions: {
          ecma: 8,
          toplevel: true,
        },
        sourceMap: true,
        cache: true,
        parallel: true,
      }),
```

And packages:

```
webpack@4.15.1
react@16.4.0
```

Going to look into it further, prod mode is a bit harder to debug obviously but I've isolated where it's happening.

**Comment by chrisbolin** [comment]
hey @natew! were you able to look into this more? definitely want to get this clear up

**Comment by VictoriaDaug** [comment]
We're having the same issue. No circular objects, seems to working fine  in dev, but throws warnings in prod. 

Currently using
`react: 16.5.2
webpack: 4.23.0
webpack-cli: 3.1.2
webpack-dev-server: 3.1.10`

**Comment by chrisbolin** [comment]
@VictoriaDaug thank you so much for reporting this. do you by chance have a quick reproduction? e.g. a minimal repository or a codesandbox? i don't think it's webpack related, probably just react-dev vs. react-prod

**Comment by xaviergonz** [comment]
I'd use terser rather than uglify-es (which is most probably what it is using)
uglify-es is deprecated and has known minification bugs for es6 code

https://github.com/webpack-contrib/terser-webpack-plugin

**Comment by chrisbolin** [comment]
@natew @VictoriaDaug 
I haven't been able to reproduce this yet. I've tried CRA, ejected CRA, and webpack with Uglify (instead of terser). Do you have any code I could use to reproduce the issue so I can debug it?

**Comment by chrisbolin** [comment]
(hit "Close and comment" by mistake 😛)

**Comment by chrisbolin** [comment]
here are my attempts at reproducing the bug. so far I _haven't been able to reproduce it_. I would love some help!
- [create-react-app](https://github.com/chrisbolin/react-fast-compare-bug-reproductions/tree/issue-30-circ-ref-cra)
- [webpack with terser](https://github.com/chrisbolin/react-fast-compare-bug-reproductions/tree/issue-30-circ-ref-eject)
- [webpack with uglify](https://github.com/chrisbolin/react-fast-compare-bug-reproductions/tree/issue-30-circ-ref-uglify)

**Comment by chrisbolin** [comment]
@xaviergonz have you seen this issue with react-fact-compare by chance?

**Comment by ecnaidar** [comment]
@chrisbolin That seems do do the trick https://github.com/ecnaidar/victory-repr

**Comment by ryan-roemer** [comment]
Also tried this with `react-fast-compare@2.0.1` and did **not** get the `console.warn` message.

If someone can get us a reproduction like @ecnaidar so wonderfully put together but with `react-fast-compare@2.0.4+` that would be super useful for us digging in and figuring things out. Thanks!!!

**Comment by chrisbolin** [comment]
@ecnaidar thank you again for the bug reproduction. The core issue is that you are using `victory@0.26.1`, which depends on `react-fast-compare@^1.0.0`, which _has this RangeError bug_.

Available solutions, in order of preference:
- preferred: upgrade to [`victory@0.27.0`](https://github.com/FormidableLabs/victory/blob/master/CHANGELOG.md#0270-2018-06-05) (or greater!), which upgraded `react-fast-compare`
- if you are using `yarn`: manually add a `resolutions` for `"react-fast-compare": "2.0.4"`. See Ryan's example above
- if can can't upgrade: downgrade to [`victory@0.25.7`](https://github.com/FormidableLabs/victory/blob/master/CHANGELOG.md#0257-2018-03-27) which did not contain `react-fast-compare` at all

**Comment by vientang** [comment]
Hi, 

I'm getting this error too. "Warning: react-fast-compare does not handle circular references. Error Out of stack space". 

Here's a very light representation of my set up - https://codesandbox.io/s/lyjkk9lnrq

The error only shows up on IE11. Chrome, Firefox and Safari are fine. I'm using this package standalone, not with Victory, mainly b/c I was sold on the speed! 

Let me know if you need any other information.

**Comment by chrisbolin** [comment]
@vientang thanks for the reproduction on CodeSandbox - that's _very_ helpful!

**Comment by chrisbolin** [comment]
@vientang I haven't gotten IE11 to even run CodeSandbox. i can't find official support information for it, but it fails in babel:
![image](https://user-images.githubusercontent.com/2822048/49825443-ad7aae00-fd41-11e8-86a6-9be517baf838.png)
Sorry, I'm trying to do this without setting up a development environment on windows :P

**Comment by chrisbolin** [comment]
tools like http://browserling.com are really helpful!

**Comment by Scritik** [comment]
@chrisbolin I have the same issue so I made a CodeSandbox to show you. I use `react-redux` to build some data with circular refs but the demo is using the latest version of `react-fast-compare` directly to compare the data.

https://codesandbox.io/s/react-fast-compare-demo-8z67e

**Comment by chrisbolin** [comment]
@Scritik did you leave a comment and then delete it? I'm just trying to follow up. This is the comment I got an email notification about...

> @chrisbolin I have the same issue so I made a CodeSandbox to show you. I use react-redux to build some data with circular refs but the demo is using the latest version of react-fast-compare directly to compare the data. https://codesandbox.io/s/react-fast-compare-demo-8z67e

**Comment by Scritik** [comment]
@chrisbolin Yeah, sorry. Forget about this, I mixed multiple things and the issue is not with `react-fast-compare` ;)

**Comment by chrisbolin** [comment]
we haven't had any reports of this in a long while, so i'm going to close for now
