### ISSUE TITLE
JSON parse JSON stringify speed test

### ISSUE THREAD

**Issue by ErkanSensei** [FormidableLabs/react-fast-compare#35]
How does the speed of this compare to using `JSON.parse(JSON.stringify(obj)) === JSON.parse(JSON.stringify(obj2))`?

**Comment by chrisbolin** [comment]
hey @ErkanSensei! i'm honestly not sure. I'd guess that parse/stringify would have a bit more overhead, but I've been surprised by javascript before :D 

if you add it to the [benchmark suite](https://github.com/FormidableLabs/react-fast-compare/blob/master/benchmark/index.js#L10) i'm happy to merge it!

**Comment by SashaKoro** [comment]
@chrisbolin Looks like this conversation is from a year and a half ago, but I'm interested in adding that comparison to the benchmark suite. Will you still accept a pull request?

**Comment by chrisbolin** [comment]
For sure!

**Comment by SashaKoro** [comment]
After looking into it, this comparison actually fits better in the [fast-deep-equal](https://github.com/epoberezkin/fast-deep-equal) repo. A `JSON.stringify(obj1) === JSON.stringify(obj2)` comparison cannot handle circular references and should never be used when data might contain React components. It's also pretty slow when running generic data, as well as susceptible to giving false positives in many other cases.

```
--- speed tests: generic usage ---

react-fast-compare x 160,023 ops/sec ±0.88% (90 runs sampled)
fast-deep-equal x 158,356 ops/sec ±0.31% (94 runs sampled)
lodash.isEqual x 34,607 ops/sec ±0.52% (94 runs sampled)
nano-equal x 162,973 ops/sec ±0.38% (94 runs sampled)
shallow-equal-fuzzy x 135,792 ops/sec ±0.39% (92 runs sampled)
JSON.stringify x 23,047 ops/sec ±0.56% (94 runs sampled)
```

```
JSON.stringify
- different result: JSON.stringify scalars Infinity and -Infinity are not equal
- different result: JSON.stringify objects equal objects (different properties "order")
- different result: JSON.stringify objects object with extra undefined properties are not equal #1
- different result: JSON.stringify objects object with extra undefined properties are not equal #2
- different result: JSON.stringify objects object with extra undefined properties are not equal #3
- different result: JSON.stringify Date objects date and string are not equal
- different result: JSON.stringify RegExp objects not equal RegExp objects (different pattern)
- different result: JSON.stringify RegExp objects not equal RegExp objects (different flags)
- different result: JSON.stringify RegExp objects RegExp and object are not equal
- different result: JSON.stringify functions different functions are not equal
- different result: JSON.stringify sample objects big object
- error: React elements an element compared with itself Converting circular structure to JSON
- error: React elements two elements equal by value Converting circular structure to JSON
- error: React elements two elements unequal by value Converting circular structure to JSON
```

**Comment by chrisbolin** [comment]
@SashaKoro agreed. And thanks for posting the results- that’s really interesting!
