### ISSUE TITLE
Breaking in React-Native - Variable 'Element' missing

### ISSUE THREAD

**Issue by rimzici** [FormidableLabs/react-fast-compare#38]
I think the recent [commit](https://github.com/FormidableLabs/react-fast-compare/commit/f26b6c52ba6a4027ad18a438c08f88c9b5c734bf) has introduced some compatibility issues in RN.

![screenshot_20181109-195845](https://user-images.githubusercontent.com/16771765/48268344-b8000a00-e45a-11e8-85b0-70f0db81f4d5.png)

v2.0.1 - works fine
v2.0.3 - crash

Thanks!

**Comment by chrisbolin** [comment]
Thanks for the heads up! We don’t have any automated RN tests, so this was
a blind spot

**Comment by chrisbolin** [comment]
@boygirl heads up, i broke you 😭

**Comment by pgom** [comment]
:) maybe a regular check for existence of `Element`, will do no?

**Comment by chrisbolin** [comment]
@pgom and @rimzici -
could you try this patch locally so we can verify it works? In your `node_modules` find `react-fast-compare` and inside of `index.js` replace
```
var inBrowser = typeof window === 'object';
```
with
```
var inBrowser = typeof Element === 'function';
```

**Comment by pgom** [comment]
@chrisbolin that works fine

**Comment by chrisbolin** [comment]
sounds great. #39 will fix this. i'll let CI pass and then release it as 2.0.4. thanks for your help!

**Comment by pgom** [comment]
No problem. Thanks for looking at this so quickly.

**Comment by chrisbolin** [comment]
@rimzici @pgom this should be completely fixed. try reinstalling (you should get `react-fast-compare@2.0.4` in your deps)

@boygirl i think i unbroke victory-native 😅
