### ISSUE TITLE
Working with Immutable.js structures

### ISSUE THREAD

**Issue by jamesopti** [FormidableLabs/react-fast-compare#42]
### Summary

The project where I'd like to use this package uses [ImmutableJS](https://github.com/immutable-js/immutable-js) for many of its data collections, which are often passed to React as props.

If I were to use this in that library, what would be the best way to handle ImmutableJS comparisons, where the [Immutable.is](https://immutable-js.github.io/immutable-js/docs/#/is) method is preferred.

Thanks!

**Comment by chrisbolin** [comment]
Great question! How about just writing a custom function like this...

```js
var isEqual = require("react-fast-compare");
const { Map, is } = require("immutable");

function extendedIsEqual(a, b) {
  // try Immutable
  if (is(a, b)) return true;
  // try react-fast-compare
  if (isEqual(a, b)) return true;
  // recurse Object-like entities
  if (a && b && typeof a == "object" && typeof b == "object") {
    var keys = Object.keys(a);
    for (var i = keys.length; i-- !== 0; ) {
      var key = keys[i];
      if (!extendedIsEqual(a[key], b[key])) return false;
    }
    return true;
  }
  return a === b;
}
```

Here's a demo of it: https://codesandbox.io/s/0o4n312kmp (see the Terminal output).

**Comment by chrisbolin** [comment]
closing this, as a we have a workaround AND the new v3 is focused on ES6 support, speed, and bundle size. there's just not room for custom support for immutable
