### ISSUE TITLE
TypeScript library for react-fast-compare?

### ISSUE THREAD

**Issue by willsmanley** [FormidableLabs/react-fast-compare#58]
I know that the docs suggest `isEqual` as the default export name for this package, but its not being picked up by my IDE for completion suggestions (PhpStorm)

**Comment by ryan-roemer** [comment]
Hopefully this can help you: https://github.com/FormidableLabs/react-fast-compare/blob/master/index.d.ts (`exportedEqual`)

**Comment by willsmanley** [comment]
Nice, thanks Ryan! Even while using exportedEqual as the import name, PhpStorm doesn't seem to autosuggest importing the package. Are there any typescript libraries for react-fast-compare?

**Comment by chrisbolin** [comment]
Maybe i'm misunderstanding your question, but https://github.com/FormidableLabs/react-fast-compare/blob/master/index.d.ts _is_ the types files for this library

**Comment by chrisbolin** [comment]
you should see it in your node_modules. if your editor doesn't pick that up, then we should troubleshoot and see what the criteria is for types in that editor

**Comment by ryan-roemer** [comment]
@chrisbolin -- I went looking a little bit more and I think we may have an unreleased fix:

- master: https://github.com/FormidableLabs/react-fast-compare/blob/master/index.d.ts
- latest release: https://unpkg.com/react-fast-compare@2.0.4/index.d.ts

**Comment by chrisbolin** [comment]
Bingo! @willsmanley as luck would have it we are releasing 3.0.0 later today, so you can upgrade to get those types.

**Comment by chrisbolin** [comment]
also, `exportedEqual` is a dumb name 😂  I'm going to change it to `isEqual`

**Comment by chrisbolin** [comment]
@willsmanley could you test out our beta (https://www.npmjs.com/package/react-fast-compare/v/3.0.0-beta.1) and see if your editor picks up the name? (it would be `exportedEqual` in that beta)

**Comment by chrisbolin** [comment]
Alright, we've validated the autocomplete in WebStorm (thx @carlos-kelly) and VSCode.

WebStorm:

![image](https://user-images.githubusercontent.com/2822048/73881779-2da18400-481e-11ea-9b1f-606a13c78be6.png)

VS Code:

![image](https://user-images.githubusercontent.com/2822048/73881889-693c4e00-481e-11ea-964d-c7295584b07e.png)

Closing, as this is fixed in `react-fast-compare@3.0.0-beta.1`
