### ISSUE TITLE
Fix exported types so that they work for react-redux

### ISSUE THREAD

**Issue by marqu3z** [FormidableLabs/react-fast-compare#61]
It seems the typing for react redux hook `useSelector` relies on the types of the equality function to infer the return type:

```typescript
// @types/react-redux/index.d.ts
export function useSelector<TState, TSelected>(
    selector: (state: TState) => TSelected,
    equalityFn?: (left: TSelected, right: TSelected) => boolean
): TSelected;
```

Using `isEqual` as equality function the compiler will infer `any` as `TSelected` type because:
```typescript
declare module 'react-fast-compare' {
  const isEqual: (a: any, b: any) => boolean
  export default isEqual
}
```

So 
```typescript
const selector = (state: State): DeepObject => {a: { b: [1,2,3] } }
const value = useSelector(selector) // typed correctly as DeepObject
const value = useSelector(selector, isEqual) // typed as any
```

Declaring `isEqual` with generic types should solve the issue
```typescript
declare module 'react-fast-compare' {
  const isEqual: <A, B>(a: A, b: B) => boolean
  export default isEqual
}
```

**Comment by chrisbolin** [comment]
thanks @marqu3z! I'll look into this as soon as I can. I might cut a beta release—would you be willing to test that?

**Comment by kitten** [comment]
@chrisbolin We may be able to retain support as it was before but satisfy typings like these by using: `<A = any, B = any>(a: A, b: B) => boolean`

**Comment by marqu3z** [comment]
> thanks @marqu3z! I'll look into this as soon as I can. I might cut a beta release—would you be willing to test that?

Sure, no problem

**Comment by chrisbolin** [comment]
see https://github.com/FormidableLabs/react-fast-compare/pull/62 as well. We may be able to use kitten's `<A = any, B = any>(a: A, b: B) => boolean`, but we may have to use `(a: any, b: any): boolean`. Some testing will be needed, and I think we should release a beta and have folks try it.

**Comment by chrisbolin** [comment]
**Important note:** in order to fix the types, we need to give up the naive hope that we could ever types that statically do a comparison. e.g. 

```ts
<Thing = any>(<a: Thing, b: Thing>) => boolean
```

We've dealt with this earlier, so I want to make sure it doesn't come back to bite us.

**Comment by kale-stew** [comment]
@chrisbolin the more I'm reading about namespace declaration, the more it seems our types are _definitely_ broken as-is. With the namespace declaration being dead code, I'm not confident it's working the way we think it is?

[More info about ambient namespaces / namespacing in general](https://www.typescriptlang.org/docs/handbook/namespaces.html#ambient-namespaces)

**Comment by cdierkens** [comment]
> @kale-stew kale-stew moved this from In progress to Done in May 2020 on May 28, 2020

@ryan-roemer this might be closable as well. We may not have had the automation turned on to set this ticket to closed when moving the card on the project board.

**Comment by ryan-roemer** [comment]
Sounds good!
