### ISSUE TITLE
Ignore Arrow Functions

### ISSUE THREAD

**Issue by tyherox** [FormidableLabs/react-fast-compare#78]
Hello, thanks for the awesome library.

I was wondering if there was an option to ignore arrow / anonymous function values since they always return false (as mentioned by what @chrisbolin wrote [here](https://github.com/FormidableLabs/react-fast-compare/issues/45#issuecomment-496272644)).

Thanks again!

**Comment by chrisbolin** [comment]
hi @tyherox! while you can't ignore functions in the current version, you could try version `1.0.0` which _did_ treat functions as equal - see the changelog https://github.com/FormidableLabs/react-fast-compare/blob/master/CHANGELOG.md#200-2018-06-04
