### ISSUE TITLE
Re-evaluate project's eslint rules

### ISSUE THREAD

**Issue by kale-stew** [FormidableLabs/react-fast-compare#79]
We have not one but _three_ different ymls with eslint configs. We should re-evaluate these, remove the extras where unnecessary and maybe clean up specific overrides for our test dirs.

1. Root config: [here](https://github.com/FormidableLabs/react-fast-compare/blob/master/.eslintrc.yml)
2. Benchmark test config: [here](https://github.com/FormidableLabs/react-fast-compare/blob/master/benchmark/.eslintrc.yml)
3. Node/browser test config: [here](https://github.com/FormidableLabs/react-fast-compare/blob/master/test/.eslintrc.yml)

**Comment by ryan-roemer** [comment]
The root + test one is a very normal, pretty much expected thing to have. The benchmark one could probably be removed and replaced inline with control comments.
