### ISSUE TITLE
Update benchmark png

### ISSUE THREAD

**Issue by kale-stew** [FormidableLabs/react-fast-compare#81]
1. We should use [`victory-cli`](https://www.npmjs.com/package/victory-cli) to generate an svg based on the benchmarks
2. This should live in the `benchmark` npm script for easy manual updates
3. The chart should also show which version of each library we are comparing rfc to

#### Libraries to include in the comparison

- `fast-deep-equal` (latest v: 3.1.1)
- `shallow-equal-fuzzy` (latest v: 0.0.2)
- `nano-equal` (latest v: 2.0.2)
- `lodash.isEqual` (latest v: 4.5.0)

**Comment by chrisbolin** [comment]
> Next, install librsvg, which is a dependency for this library to work 

ah, that might make our lives miserable eh? let's make sure that `yarn run benchmark` just skips the chart generation for people that don't have this dependency.
