### ISSUE TITLE
CJS + ESM Question/discussion

### ISSUE THREAD

**Issue by apipkin** [FormidableLabs/react-fast-compare#84]
React Popper pulls in via `import isEqual from 'react-fast-compare';` and this is failing in Rollupjs which states `default is not exported from [module]`. 

Would it be possible for the package that is released to npm contain a `cjs` and an `esm` file? This would allow for `require()` statements as well as `import`. 

I'll happily put a PR together if this is desired, but wanted to know where the thoughts were in the project before putting in the effort.

I have this working now using `patch-package` with the following patch:
```
diff --git a/node_modules/react-fast-compare/index.js b/node_modules/react-fast-compare/index.js
index 1301ff0..3fa4874 100644
--- a/node_modules/react-fast-compare/index.js
+++ b/node_modules/react-fast-compare/index.js
@@ -115,7 +115,7 @@ function equal(a, b) {
 }
 // end fast-deep-equal
 
-module.exports = function isEqual(a, b) {
+function isEqual(a, b) {
   try {
     return equal(a, b);
   } catch (error) {
@@ -132,3 +132,5 @@ module.exports = function isEqual(a, b) {
     throw error;
   }
 };
+
+export default isEqual;
```

**Comment by ryan-roemer** [comment]
Can you provide a small reproduction for us? I was under the impression rollup can handle CJS deps with a plugin or something?

**Comment by apipkin** [comment]
Yeah, that was my impression as well. I believe it has to do with the import in a node_module pulling in another node module. It may be that rollup only goes so far `*shrug*

I ended up rebuilding the entire rollup js file (to ensure all packages were up to date) and ended up with this list of plugins:

```
const plugins = [
  replace({
    'process.env.NODE_ENV': JSON.stringify(
      process.env.NODE_ENV || 'production'
    ),
  }),
  resolve(),
  svgr(),
  json(),
  url(),
  postcss({
    extract: true,
    plugins: [
      simplevars(),
      nested(),
      autoprefixer(),
      cssnext({ warnForDuplicates: false }),
    ],
  }),
  babel({
    babelHelpers: 'bundled',
    exclude: 'node_modules/**',
  }),
  peerDepsExternal({
    includeDependencies: true,
  }),
  commonjs({
    include: /node_modules/,
  }),
  autoNamedExports(),
  isProduction && terser(),
];
```

I'll work on a small reproduction, but will not be near my computer to do so (after today) until next Monday, so there may be a slight delay here. 

I also added a discussion over in the Popper Spectrum chat to (hopefully) get insight from them: https://spectrum.chat/popper-js/react-popper/getting-error-when-using-rollup-due-to-import-without-default~45c053ae-4442-4502-9f07-8f970aa41649

**Comment by chrisbolin** [comment]
to answer the original question, our goal is to keep `react-fast-compare` small and minimal, and to _only provide a commonjs dist_.

hopefully for your case we can find the proper configuration for [@rollup/plugin-commonjs](https://github.com/rollup/plugins/tree/master/packages/commonjs). To echo @kitten, in their docs they have [this note](https://github.com/rollup/plugins/tree/master/packages/commonjs#using-with-rollupplugin-node-resolve), which explicitly uses `@rollup/plugin-commonjs` directly after `@rollup/plugin-node-resolve`:
```js
plugins: [resolve(), commonjs()]
```

(happy to keep discussing in this issue, but i will also close it, as we have no ESM plans)

**Comment by apipkin** [comment]
Thanks so much for the assistance and answering the question! I'll be diving into this more and hope the suggestions mentioned work!
