### ISSUE TITLE
Infra: Switch to GitHub Actions

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/react-fast-compare#93]
- [ ] Replace Travis/Appveyor
- [ ] Set up GH actions for linux and windows builds

**Comment by kitten** [comment]
@ryan-roemer I've just taken a quick look at what needs to be replaced from Travis, and while it's not super complicated, are the tests in this repo (e.g. the in-browser karma tests) potentially a little overkill? I mean, the highest risk is always "does it work in IE11" and it's not like we'd want to add that to CI necessarily 😅 Maybe we can remove some of these from CI?

**Comment by ryan-roemer** [comment]
I'm just looking for an easy step 1 of "switch to GH actions" and then maybe ticket out future work. As long as the existing tests work, I don't think we need to change anything immediately for stuff.
